version: '3.1'

services:
  nginx:
    extends:
      file: docker-compose.base.yml
      service: nginx
      
  reactjs:
    extends:
      file: docker-compose.base.yml
      service: reactjs

  node:
    extends:
      file: docker-compose.base.yml
      service: node

  mongo:
    extends:
      file: docker-compose.base.yml
      service: mongo


networks:
  cafenetwork:
    name: cafenetwork
    driver: "bridge"